.SUFFIXES : .class .java


.java.class : 
	javac $(JAVAFLAGS) $*.java

all: Attribute.class \
BadAttributeException.class \
BadClassFileException.class \
BadConstantException.class \
BadConstantTagException.class \
Bytecodes.class \
ClassFile.class \
ClassFileException.class \
CodeAttribute.class \
ConstantClass.class \
ConstantDouble.class \
ConstantFieldref.class \
ConstantFloat.class \
ConstantInteger.class \
ConstantInterfaceMethodref.class \
ConstantLong.class \
ConstantMethodref.class \
ConstantNameAndType.class \
ConstantRef.class \
ConstantString.class \
ConstantUtf8.class \
ConstantValueAttribute.class \
ExceptionTableEntry.class \
ExceptionsAttribute.class \
FieldInfo.class \
FieldOrMethodInfo.class \
GenericConstant.class \
InnerClassesAttribute.class \
JavaClass.class \
LineNumberTableAttribute.class \
LineNumberTableEntry.class \
LocalVariableTableAttribute.class \
LocalVariableTableEntry.class \
MethodInfo.class \
NameSource.class \
RuntimeConstants.class \
SourceFileAttribute.class \
Stringer.class \
UndefinedLabelException.class \
UnrecognizedAttribute.class 



