.SUFFIXES : .class .java


.java.class : 
	javac $(JAVAFLAGS) $*.java

all:  \
BindingEnv.class \
ByteArrayClassLoader.class \
CompiledProcedure.class \
Complex.class \
Cons.class \
Naming.class \
NotAConsException.class \
Numbers.class \
Promise.class \
Rational.class \
ReadEvalPrint.class \
Reader.class \
SchemeCompiler.class \
SchemeException.class \
SchemeLibrary.class \
SchemeReader.class \
Symbol.class \
SyntaxError.class \
UnboundException.class \
WrongNumberOfArgsException.class 

