.SUFFIXES : .class .java


.java.class : 
	javac $(JAVAFLAGS) $*.java

all:  Cons.class \
Prolog.class \
PrologCompiler.class \
PrologParser.class \
Structure.class \
SyntaxError.class \
Var.class 


